# Stage 1: Build Stage
FROM oven/bun:latest AS build

ARG TURBO_TEAM
ARG TURBO_TOKEN
ARG NUXT_PRIVATE_GITHUB_TOKEN
ARG NUXT_PUBLIC_STUDIO_TOKENS
ARG NUXT_PUBLIC_SITE_URL
ARG NUXT_PUBLIC_MEETING_LINK
ARG NUXT_PRIVATE_RESEND_API_KEY
ARG NUXT_PRIVATE_NOTES_PASSWORD

ENV TURBO_TEAM=$TURBO_TEAM
ENV TURBO_TOKEN=$TURBO_TOKEN
ENV NUXT_PRIVATE_GITHUB_TOKEN=$NUXT_PRIVATE_GITHUB_TOKEN
ENV NUXT_PUBLIC_STUDIO_TOKENS=$NUXT_PUBLIC_STUDIO_TOKENS
ENV NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL
ENV NUXT_PUBLIC_MEETING_LINK=$NUXT_PUBLIC_MEETING_LINK
ENV NUXT_PRIVATE_RESEND_API_KEY=$NUXT_PRIVATE_RESEND_API_KEY
ENV NUXT_PRIVATE_NOTES_PASSWORD=$NUXT_PRIVATE_NOTES_PASSWORD
ENV NODE_ENV=production

WORKDIR /app

COPY package.json ./
COPY bun.lockb ./

COPY . .

RUN bun install

RUN bun run build

# Stage 2: Final Stage
FROM oven/bun:latest

WORKDIR /app

COPY --from=build /app/.output .output

EXPOSE 3000

CMD ["bun", "run", ".output/server/index.mjs"]
