import { Sandbox } from '@vercel/sandbox'
import { stepCountIs, ToolLoopAgent } from 'ai'
import { writeToSandbox, syncToGit, INTELLIGENCE_MODEL } from '../utils'

const SANDBOX_NAME = 'hr-folio-intelligence'

const ANGLE_SELECTOR_INSTRUCTIONS = [
  'You are an editorial filter for Hugo (@hugorcd), a developer and open-source creator.',
  '',
  'You receive raw intelligence data: GitHub activity, Linear completions, Typefully posts (Hugo\'s published tweets verbatim), and previous tweet suggestions.',
  '',
  'Your only job: decide what is genuinely worth tweeting. Default answer is no.',
  '',
  '## Hard disqualifiers — reject immediately, no exceptions',
  '',
  '- Test-only changes, test overhauls, CI fixes — nobody cares',
  '- Dependency bumps, chore commits, lint fixes',
  '- PRs not yet merged into main/master',
  '- Anything with an issue number or ticket ID as the story (e.g. "evlog #338 ...")',
  '- In-progress or upcoming Linear issues — only completed/done',
  '- Already covered in a previous tweets output',
  '- A topic that any developer could tweet without knowing Hugo personally',
  '',
  '## What passes',
  '',
  'An angle must clear at least one of these:',
  '- Something genuinely shipped (merged PR, published release, deployed feature) with a non-obvious story behind it',
  '- A concrete technical decision or tradeoff that has a real payoff for the reader',
  '- A specific observation about Hugo\'s own project that only he could make (community signal, unexpected edge, a thing that broke in an interesting way)',
  '',
  '## Output',
  '',
  'Return 2–4 angles maximum. If you can only find 1 genuinely good angle, return 1.',
  'For each angle:',
  '- One-line angle description (no PR numbers, no issue numbers)',
  '- One sentence: what makes this specific to Hugo and worth reading',
  '- One sentence: likely format (one-liner, 2-3 lines, thread)',
  '',
  'If nothing clears the bar, return: "Nothing worth tweeting today."',
].join('\n')

const TWEET_WRITER_INSTRUCTIONS = [
  'You are a ghostwriter for Hugo (@hugorcd), a developer and open-source creator.',
  'You receive: Hugo\'s real published tweets with engagement stats, selected editorial angles, and activity context.',
  '',
  '## Step 1 — Analyse the voice corpus (do this in your reasoning, not in the output)',
  '',
  'Before writing a single word, read ALL of Hugo\'s published tweets. Then note:',
  '1. His 3 most common opening patterns — exact words or structures he uses to start',
  '2. Typical line length and line break usage',
  '3. Punctuation: does he end lines with periods? Use commas mid-line? Lowercase everything?',
  '4. His specific word choices: "just", "shipped", "dropped", bare project names, no filler',
  '5. The 3 tweets with the highest impressions — what made them work structurally?',
  '',
  'Only after this analysis, write the tweets. Every draft must pass: "Could only Hugo have written this?"',
  '',
  '## Step 2 — Write',
  '',
  '## What not to do',
  '',
  '- No "hook line + bullet list + link" structure',
  '- No generic dev wisdom. His tweets are about what he\'s actually doing right now.',
  '- No issue numbers, PR numbers, internal ticket IDs',
  '- No fake URLs. Only use links that appear explicitly in the data.',
  '- No work-in-progress tweets. Shipped and merged only.',
  '- No style analysis in the output.',
  '- No trailing commas. No incomplete sentences. Every tweet is a complete thought.',
  '- No abstract openers ("The library...", "The framework...", "The tooling...")',
  '- No bullet-list tweets unless Hugo genuinely uses that format (check the corpus)',
  '',
  '## Output format',
  '',
  'Produce **4–6 tweets**. Each must be complete and publishable as-is.',
  '',
  'For each tweet, use a short heading followed by the tweet text in a fenced code block:',
  '',
  '### [project or topic] — [one-word angle]',
  '',
  '```',
  '[tweet text here]',
  '```',
  '',
  'Vary the rhythm. Mix one-liners with multi-line posts. If one angle clearly warrants a thread (3–5 parts), write it — but only one thread maximum, and only if the topic genuinely needs the space.',
  '',
  '## Links',
  '',
  'Add a link when the tweet references something the reader can go look at. GitHub URL, npm URL, docs URL — whatever is most direct. Bare URL, no "check it out →" padding unless that\'s how Hugo writes it.',
  '',
  '## Constraints',
  '',
  '- Only write tweets for the angles selected by the editorial filter.',
  '- Don\'t add angles the filter rejected.',
  '- Don\'t repeat tweets already published or scheduled in Typefully.',
].join('\n')

const TWEET_CRITIC_INSTRUCTIONS = [
  'You are a brutally honest editor reviewing tweet drafts written for Hugo (@hugorcd), a developer and open-source creator.',
  '',
  'You receive two things:',
  '- Hugo\'s actual published tweets (verbatim, from the Typefully data) — your reference for what good looks like',
  '- A set of draft tweets generated by an AI ghostwriter',
  '',
  '## Your job',
  '',
  'Score each draft tweet from 1 to 5 and explain why.',
  '',
  '**Score definitions:**',
  '- 5 — Publish as-is. Sounds exactly like Hugo. Specific, honest, worth reading.',
  '- 4 — Good but needs a small tweak (one word off, slightly too long, link missing).',
  '- 3 — The angle is right but the execution is off — too generic, wrong tone, padded.',
  '- 2 — The angle is weak or the writing is clearly AI. Needs a full rewrite.',
  '- 1 — Drop it. Either the topic isn\'t tweet-worthy or it\'s impossible to fix.',
  '',
  '## Scoring criteria',
  '',
  'Compare each draft against Hugo\'s real tweets. Ask:',
  '- Would Hugo actually post this? Or does it feel like content?',
  '- Is it specific to what Hugo is building, or could any developer have written it?',
  '- Does it open well, or does it start with a generic hook?',
  '- Is it the right length for what it\'s saying, or is it padded / too compressed?',
  '- Does it use Hugo\'s actual patterns (lowercase, short lines, dashes, bare links) or a different style?',
  '',
  '## Output format',
  '',
  'For each tweet, output:',
  '',
  '### [original tweet heading]',
  '**Score: X/5**',
  '[2–4 sentences of specific critique. What works, what doesn\'t, and what would fix it.]',
  '',
  'End with a short summary: how many are ready to publish, how many need revision, how many should be dropped.',
].join('\n')

const TWEET_REFINER_INSTRUCTIONS = [
  'You are a ghostwriter for Hugo (@hugorcd). You receive:',
  '1. The original draft tweets',
  '2. A critique with scores (1–5) for each draft',
  '3. The full context, including Hugo\'s actual published tweets verbatim (your style reference)',
  '',
  '## Your job',
  '',
  'Produce the final tweet set.',
  '',
  '- Score 5 or 4: keep as-is or apply the small fix mentioned in the critique',
  '- Score 3: rewrite from scratch using the same angle but with better execution',
  '- Score 2: rewrite from scratch — different approach, same topic if still worth it',
  '- Score 1: drop entirely, do not include in output',
  '',
  'Apply the same voice rules as the original writer:',
  '- Study Hugo\'s actual published tweets before writing. Not descriptions, the real words.',
  '- If the tweet could have been written by any developer without knowing Hugo, it\'s wrong.',
  '- No hook + bullet list + link structure.',
  '- No issue numbers or PR numbers.',
  '- No fake URLs.',
  '- No style analysis in the output.',
  '',
  '## Output format',
  '',
  'First, a short "Edit notes" section summarizing what you changed and why (3–5 bullet points max).',
  '',
  'Then the final tweets, using the same format as the drafts:',
  '',
  '### [project or topic] — [one-word angle]',
  '',
  '```',
  '[final tweet text]',
  '```',
].join('\n')

export async function tweetsWorkflow(date: string) {
  'use workflow'

  const [context, publishedTweets] = await Promise.all([
    gatherContext(date),
    fetchPublishedTweets(),
  ])
  if (!context) throw new Error('[tweets] No context found in sandbox — ensure daily workflows have run first.')

  const angles = await selectAngles(context, publishedTweets, date)
  const drafts = await generateTweets(context, publishedTweets, angles, date)
  const critique = await critiqueTweets(publishedTweets, drafts)
  const result = await refineTweets(publishedTweets, drafts, critique, date)
  await writeToSandbox('tweets', date, result)
  await syncToGit('tweets', date, result)
}

async function gatherContext(date: string): Promise<string> {
  'use step'

  let sandbox: Sandbox | undefined
  try {
    sandbox = await Sandbox.get({ name: SANDBOX_NAME })
  } catch {
    return ''
  }

  const run = async (command: string) => {
    const cmd = await sandbox!.runCommand('bash', ['-c', command])
    return (await cmd.stdout()) ?? ''
  }

  try {
    const [typefully, github, linear, previousTweets] = await Promise.all([
      run(`find typefully -name "*.md" 2>/dev/null | sort -r | head -7 | xargs cat 2>/dev/null`),
      run(`find github -name "*.md" 2>/dev/null | sort -r | head -5 | xargs cat 2>/dev/null`),
      run(`find linear -name "*.md" 2>/dev/null | sort -r | head -5 | xargs cat 2>/dev/null`),
      run(`find tweets -name "*.md" 2>/dev/null | sort -r | head -5 | xargs cat 2>/dev/null`),
    ])

    return [
      `## Typefully — last 7 days (Hugo's published tweets verbatim + drafts)\n\n${typefully || '(no data)'}`,
      `## GitHub — last 5 days\n\n${github || '(no data)'}`,
      `## Linear — last 5 days\n\n${linear || '(no data)'}`,
      `## Previous tweet outputs — last 5\n\n${previousTweets || '(no data)'}`,
    ].join('\n\n---\n\n')
  } catch {
    return ''
  }
}

async function fetchPublishedTweets(): Promise<string> {
  'use step'

  const apiKey = process.env.TYPEFULLY_API_KEY
  if (!apiKey) return '(Typefully API key not configured)'

  const base = 'https://api.typefully.com'
  const headers = { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' }

  const socialSetId = await (async () => {
    const envId = process.env.TYPEFULLY_SOCIAL_SET_ID?.trim()
    if (envId && /^\d+$/.test(envId)) return envId
    const res = await fetch(`${base}/v2/social-sets?limit=50`, { headers })
    if (!res.ok) return null
    const data = await res.json() as { results: Array<{ id: number, username: string, team?: unknown }> }
    const personal = data.results.find(s => !s.team)
    return personal ? String(personal.id) : null
  })()

  if (!socialSetId) return '(Could not resolve Typefully social set ID)'

  const today = new Date()
  const thirtyDaysAgo = new Date(today)
  thirtyDaysAgo.setDate(today.getDate() - 30)
  const fmt = (d: Date) => d.toISOString().slice(0, 10)

  type DraftSummary = { id: number, x_post_published_at: string | null, published_at: string | null }
  type DraftDetail = { id: number, platforms?: { x?: { posts?: Array<{ text: string }> } } }
  type AnalyticsPost = {
    draft_id?: number | null
    metrics?: {
      impressions?: number
      engagement?: { likes?: number, shares?: number, comments?: number }
    }
  }

  const [draftsRes, analyticsRes] = await Promise.all([
    fetch(`${base}/v2/social-sets/${socialSetId}/drafts?status=published&limit=30`, { headers }),
    fetch(`${base}/v2/social-sets/${socialSetId}/analytics/x/posts?start_date=${fmt(thirtyDaysAgo)}&end_date=${fmt(today)}&limit=100`, { headers }),
  ])

  const drafts = draftsRes.ok
    ? ((await draftsRes.json()) as { results: DraftSummary[] }).results
    : []

  const analytics = analyticsRes.ok
    ? ((await analyticsRes.json()) as { results: AnalyticsPost[] }).results
    : []

  // Fetch full text for each draft in parallel (platforms.x.posts[*].text)
  const details = await Promise.all(
    drafts.map(d =>
      fetch(`${base}/v2/social-sets/${socialSetId}/drafts/${d.id}?exclude_comment_markers=true`, { headers })
        .then(r => r.ok ? r.json() as Promise<DraftDetail> : null)
        .catch(() => null),
    ),
  )

  const metricsById = new Map(analytics.map(p => [p.draft_id, p]))

  const lines = drafts.map((d, i) => {
    const detail = details[i]
    const posts = detail?.platforms?.x?.posts ?? []
    const fullText = posts.map(p => p.text).join('\n\n---\n\n')
    const text = fullText || '(no content)'
    const date = (d.x_post_published_at ?? d.published_at)?.slice(0, 10) ?? 'unknown date'
    const m = metricsById.get(d.id)
    const stats = m
      ? `${m.metrics?.impressions ?? '?'} impressions · ${m.metrics?.engagement?.likes ?? '?'} likes · ${m.metrics?.engagement?.shares ?? '?'} RTs · ${m.metrics?.engagement?.comments ?? '?'} replies`
      : 'no analytics yet'
    return `${i + 1}. [${date}] ${stats}\n${text}`
  })

  return lines.length > 0
    ? `## Hugo's published X posts (last 30, verbatim + stats)\n\n${lines.join('\n\n')}`
    : '(No published posts found)'
}

async function selectAngles(context: string, publishedTweets: string, date: string): Promise<string> {
  'use step'

  const agent = new ToolLoopAgent({
    id: 'tweets-angle-selector',
    model: INTELLIGENCE_MODEL,
    instructions: ANGLE_SELECTOR_INSTRUCTIONS,
    stopWhen: stepCountIs(1),
  })

  const prompt = [
    '## Activity context (GitHub, Linear, previous tweet outputs)',
    '',
    context,
    '',
    '---',
    '',
    `Today is ${date}. Select the angles worth tweeting about.`,
  ].join('\n')

  const { text } = await agent.generate({ prompt })
  return text
}

async function generateTweets(context: string, publishedTweets: string, angles: string, date: string): Promise<string> {
  'use step'

  const agent = new ToolLoopAgent({
    id: 'tweets-writer',
    model: INTELLIGENCE_MODEL,
    instructions: TWEET_WRITER_INSTRUCTIONS,
    stopWhen: stepCountIs(1),
  })

  const prompt = [
    '## Hugo\'s real published tweets — verbatim with engagement stats (PRIMARY voice reference)',
    '',
    publishedTweets,
    '',
    '---',
    '',
    '## Selected angles',
    '',
    angles,
    '',
    '---',
    '',
    '## Activity context (for links and technical details)',
    '',
    context,
    '',
    '---',
    '',
    `Write tweets for ${date}.`,
  ].join('\n')

  const { text } = await agent.generate({ prompt })
  return text
}

async function critiqueTweets(publishedTweets: string, drafts: string): Promise<string> {
  'use step'

  const agent = new ToolLoopAgent({
    id: 'tweets-critic',
    model: INTELLIGENCE_MODEL,
    instructions: TWEET_CRITIC_INSTRUCTIONS,
    stopWhen: stepCountIs(1),
  })

  const prompt = [
    '## Hugo\'s real published tweets — verbatim with engagement stats (style reference)',
    '',
    publishedTweets,
    '',
    '---',
    '',
    '## Draft tweets to review',
    '',
    drafts,
    '',
    '---',
    '',
    'Score and critique each draft tweet.',
  ].join('\n')

  const { text } = await agent.generate({ prompt })
  return text
}

async function refineTweets(publishedTweets: string, drafts: string, critique: string, date: string): Promise<string> {
  'use step'

  const agent = new ToolLoopAgent({
    id: 'tweets-refiner',
    model: INTELLIGENCE_MODEL,
    instructions: TWEET_REFINER_INSTRUCTIONS,
    stopWhen: stepCountIs(1),
  })

  const prompt = [
    '## Original drafts',
    '',
    drafts,
    '',
    '---',
    '',
    '## Critique',
    '',
    critique,
    '',
    '---',
    '',
    '## Hugo\'s real published tweets — verbatim with engagement stats (voice reference)',
    '',
    publishedTweets,
    '',
    '---',
    '',
    `Produce the final tweet set for ${date}.`,
  ].join('\n')

  const { text } = await agent.generate({ prompt })
  return text
}
