name: Check if packages can be built

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUXT_BETTER_AUTH_SECRET: ${{ secrets.NUXT_BETTER_AUTH_SECRET }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠️ Build
        run: pnpm run build
